# fly.toml file generated for phyxit on 2022-12-06T16:54:34+01:00

app = "phyxit"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
